apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-volume
  labels:
    app: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
