apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      name: web-pod
      labels:
        app: web
    spec:
      containers:
      - name: web-con
        image: vimal13/apache-webserver-php
        volumeMounts:
        - name: web-pvc
          mountPath: /var/www/html
      volumes:
      - name: web-pvc
        persistentVolumeClaim:
          claimName: web-persistent-volume