apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-persistent-volume
  labels:
    app: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
